import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'

const root = join(import.meta.dirname, '..')
const src = join(root, 'src')
const app = readFileSync(join(src, 'App.vue'), 'utf8')
const api = readFileSync(join(src, 'api', 'api.js'), 'utf8')
const http = readFileSync(join(src, 'api', 'index.js'), 'utf8')
const login = readFileSync(join(src, 'components', 'LoginView.vue'), 'utf8')

assert.ok(existsSync(join(src, 'assets', 'visuals', 'login-enterprise-light-image2.png')), 'Login page should bundle the light enterprise Image2 background.')
assert.ok(app.includes('authUser'), 'App should track the authenticated user.')
assert.ok(app.includes('LoginView'), 'App should render a login view while signed out.')
assert.ok(app.includes('handleLogout'), 'App should support clearing the login session.')
assert.ok(app.includes('roleLabel'), 'Top bar should show a Chinese role label.')
assert.ok(http.includes('localStorage.getItem'), 'Axios should read the saved auth token.')
assert.ok(http.includes('Authorization'), 'Axios should attach Authorization header.')
assert.ok(api.includes('getCaptcha'), 'API module should expose captcha loading.')
assert.ok(api.includes('login'), 'API module should expose login.')
assert.ok(api.includes('getMe'), 'API module should expose current-user lookup.')
assert.ok(login.includes('login-light-shell'), 'Login page should use a light enterprise shell.')
assert.ok(login.includes('login-titlebar'), 'Login page should place the product title in a dedicated top-left title bar.')
assert.ok(login.includes('login-copy-veil'), 'Login hero copy should include a subtle readability veil over busy background imagery.')
assert.ok(login.includes('object-position: 36% center'), 'Login background should shift the illustration away from the hero text zone.')
assert.ok(login.includes('rgba(255, 255, 255, 0.86)'), 'Login hero should use a strong white scrim for text readability.')
assert.ok(!login.includes('login-brand'), 'Login page should not keep the old compact brand pill inside the hero copy.')
assert.ok(login.includes('企业知识库智能问答平台'), 'Login page should explain the product positioning in the hero title.')
assert.ok(login.includes('多知识库检索'), 'Login page should mention multi-knowledge-base retrieval.')
assert.ok(login.includes('引用证据链'), 'Login page should mention citation evidence chain.')
assert.ok(login.includes('权限访问'), 'Login page should mention permission-gated access.')
assert.ok(login.includes('持续对话'), 'Login page should mention persistent conversation capability.')
assert.ok(login.includes('算术验证码'), 'Login form should include arithmetic captcha copy.')
assert.ok(login.includes('验证码'), 'Login form should include captcha UI.')
assert.ok(login.includes("username: 'employee'"), 'Login page should prefill the employee experience account.')
assert.ok(login.includes("password: 'employee123'"), 'Login page should prefill the employee experience password.')
assert.ok(login.includes('体验账号：system / employee / employee123'), 'Login page should show only the employee experience account for local use.')
assert.ok(!login.includes('admin / admin123'), 'Login page should not expose the admin account as a default visible account.')
assert.ok(login.includes('import.meta.env.DEV'), 'Login page should show test accounts only in development.')
assert.ok(!login.includes('login-visual-card'), 'Login page should not keep decorative empty visual cards.')
assert.ok(!login.includes('visual-flow'), 'Login page should not keep empty visual flow placeholders.')
assert.ok(!/面试|演示|创建账号/.test(login), 'Login page should avoid interview, demo, and account-creation copy.')
assert.ok(login.includes('@keyframes login-beam'), 'Login page should include a visible moving light beam animation.')
assert.ok(login.includes('@keyframes login-orbit'), 'Login page should include an orbital enterprise motion layer.')
assert.ok(login.includes('@keyframes login-card-float'), 'Login page should include floating SaaS panel motion.')
assert.ok(login.includes('@keyframes login-panel-in'), 'Login page should include staged panel animation.')
assert.ok(!login.includes('background: #030712'), 'Login page should no longer use the old dark cockpit background.')

console.log('Auth UI contract checks passed')
